import Head from 'next/head'
import {useState} from "react"
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from "../components/Hero"
import Projects from '../components/Projects'
import Sidebar from '../components/Sidebar'
import Skills from '../components/Skills'


import useWindowDimensions from "../utils/useWindowDimensions"



export default function Home() {
  const window = useWindowDimensions()
  let [isOpen, setIsOpen] = useState(false);
  let isMobile = (window.width < 768)

  return (
    <div className="">
      <Head>
        <title>Portfolio | michealbergerson.com</title>
        <meta name="description" content="Generated by create next app" />
{/* Open Graph */}
<meta property="og:url" content="https://www.michaelbergerson.com/" key="ogurl" />
<meta property="og:image" content={"https://www.michaelbergerson.com/images/Portfolio.png"} key="ogimage" />
<meta property="og:site_name" content="michaelbergerson.com" key="ogsitename" />
<meta property="og:title" content="Portfolio | michealbergerson.com"key="ogtitle" />
<meta property="og:description" content="Michael Bergerson's Portfolio" key="ogdesc" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
<link rel="manifest" href="/site.webmanifest"/>
        <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
      </Head>
     
     {!isMobile ? <Sidebar/> : null}
    <main className="md:ml-sidebar">
      <div className="">
        <Hero isMobile={isMobile} isOpen={isOpen} setIsOpen={setIsOpen}/>   
        </div>
        <About/>

       <Skills/>
      <Projects/>
      <Contact/>
    </main>

     
    </div>
  )
}
