import Head from 'next/head'
import {useState} from "react"
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from "../components/Hero"
import Projects from '../components/Projects'
import Sidebar from '../components/Sidebar'
import Skills from '../components/Skills'

import useWindowDimensions from "../utils/useWindowDimensions"



export default function Home() {
  const window = useWindowDimensions()
  let [isOpen, setIsOpen] = useState(false);
  let isMobile = (window.width <= 768)

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
      </Head>
     
     {!isMobile ? <Sidebar/> : null}
    <main className="md:ml-sidebar">
      <div className="">
        <Hero isMobile={isMobile} isOpen={isOpen} setIsOpen={setIsOpen}/>   
        </div>
        <About/>

       <Skills/>
      <Projects/>
      <Contact/>
    </main>

     
    </div>
  )
}
