import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import {projectData} from "../data/projectInfo"


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
      </Head>
     
      <nav className="flex md:flex-col md:fixed md:overscroll-x-none md:h-full w-full md:w-1/6 z-10 px-4 bg-gray-500">
          
          <Link href="/"><a className="md:text-4xl text-white">Home</a></Link>
          <Link href="/"><a className="md:text-4xl text-white">Resume</a></Link>
          <Link href="/"><a className="md:text-4xl text-white">Contact</a></Link>
          <div className="flex mt-3">
          <a href="https://www.linkedin.com/in/michael-bergerson-375036108/"><span className="iconify text-3xl mr-1" data-icon="brandico-linkedin-rect" data-inline="false"></span></a>
          <a href="https://github.com/anxietyattacked"><span className="iconify text-3xl" data-icon="akar-icons:github-fill" data-inline="false"></span></a>
          </div>
        </nav>
      <main className="md:ml-sidebar">
    
        <div>

        </div>
        <div className=" grid place-content-center px-4">
          <h1 className="text-center font-bold text-xl mb-3">Skills</h1>
          <div className=" grid grid-cols-1">
          <div className="flex justify-center mb-3">
          <span className="iconify icon-r1" data-icon="logos:typescript-icon" data-inline="false"></span>
          <span className="iconify icon-r1" data-icon="grommet-icons:js" data-inline="false"></span>
          <span className="iconify icon-r1" data-icon="logos:react" data-inline="false"></span>
      
          </div>
          <div className="mb-3">
            <p className="text-center">typeScript, javascript, react, </p>
          </div>
          <div className="flex justify-center mb-3">
          <span className="iconify icon-r1" data-icon="logos:tailwindcss-icon" data-inline="false"></span>
          <span className="iconify icon-r1" data-icon="logos:d3" data-inline="false"></span>
          </div>
          </div>
        </div>
      <div className="grid gap-3 bg-gray-200 px-8">
        <h1 className="text-center font-bold text-xl mb-3">Projects</h1>
        {projectData.map(project => (
            <div key={project.name} className="grid md:grid-cols-5 justify-center mb-2">
         
            <h2 className="text-2xl mb-2 md:col-span-5">{project.name}</h2>
          <div className="relative overflow-hidden h-0 p3 col-span-1 md:col-span-2">
                <img className="absolute top-0 left-0 w-full h-full" src={project.image} alt={`${project.name} screenshot`} />
            </div>
            <div className="md:col-span-3 grid md:grid-cols-4 place-content-center">
            <p className="md:col-span-4 mx-8">Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae voluptate corrupti reiciendis sunt, corporis ipsam aut aspernatur soluta labore doloribus illum in! Iure animi nisi nemo, alias debitis tempore inventore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea libero ipsa debitis, 
            consectetur veniam quaerat perspiciatis itaque temporibus iure pariatur fugiat, culpa neque nobis nostrum earum cupiditate, nesciunt excepturi incidunt!</p>
            {project.name === "SneakerFlex" ? <p></p> : null}
            <div className="md:col-span-4 flex justify-center mt-8">
              <div className="">
              <a className="px-3 py-2 bg-blue-600 text-white text-center font-bold text-lg mr-4" href={project.Link}>Go to website</a>
              </div>
              <div className="col-span-2">
              <a className="px-3 py-2 bg-green-600 text-white text-center font-bold text-lg" href={project.ghLink}>Go to Github</a>
              </div>
           </div>
           <div className="md:col-span-4 mt-3">
             <p className="text-center"><strong>Frontend: </strong>{project.tech}</p>
             {project.techB ? <p className="text-center"><strong>Backend: </strong>{project.techB}</p>: null}
           </div>
            </div>
          </div>
            ))}
        
      </div>

      </main>

     
    </div>
  )
}
